const types ={

    REGISTER_REQUEST : "REGISTER_REQUEST",
    REGISTER_SUCCESS : "REGISTER_SUCCESS",
    REGISTER_FAILURE : "REGISTER_FAILURE",

    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE",

    BLOG_LIST_REQUEST : "BLOG_LIST_REQUEST",
    BLOG_LIST_SUCCESS : "BLOG_LIST_SUCCESS",
    BLOG_LIST_FAILURE : "BLOG_LIST_FAILURE",

    ARTICLE_REQUEST : "ARTICLE_REQUEST",
    ARTICLE_SUCCESS : "ARTICLE_SUCCESS",
    ARTICLE_FAILURE : "ARTICLE_FAILURE",
}

export default types;